# repo: https://github.com/kentaro-m/auto-assign-action

addReviewers: true
addAssignees: false
numberOfReviewers: 1
useReviewGroups: true

reviewGroups:
  groupA:
    - joomlagergerman/reviewer

useAssigneeGroups: false
