# repo: https://github.com/kentaro-m/auto-assign-action

addReviewers: true
reviewers:
    - tecpromotion
    - zero-24
    - coolwebcreations

numberOfReviewers: 0
useAssigneeGroups: false
addAssignees: author
