name: Bug Report
description: Einen Verbesserungsvorschlag oder Fehler melden.
title: "[3.10/4.x] "
labels: ["enhancement"]
assignees:
  - tecpromotion
  - zero-24
  - heelc29
body:
  - type: markdown
    attributes:
      value: |
        Vielen Dank, dass Du dir Zeit nimmst, diesen Vorschlag bzw. Fehler mit der Community zu teilen.
  - type: textarea
    id: what-happened
    attributes:
      label: Was soll verbessert / korrigiert werden?
      description: Bitte beschreibe möglichst ausführlich, **warum** etwas verbessert oder korrigiert werden soll.
      placeholder: Gerne mit Screenshots und Fehlermeldungen!
    validations:
      required: true
  - type: textarea
    id: where-happened
    attributes:
      label: Wo wird der Sprachstring angezeigt (Frontend/Backend)
      description: Bitte beschreibe möglichst ausführlich die Stelle, **wo** etwas verbessert oder korrigiert werden soll.
      placeholder: Gerne mit Screenshots und Fehlermeldungen!
    validations:
      required: true
  - type: textarea
    id: new-translation
    attributes:
      label: Was wäre eine bessere Übersetzung / Bezeichnung
      description: Hier ist Platz für deinen Vorschlag.
      placeholder: Gerne mit Screenshots wie dies im Front- oder Backend dann aussehen kann!
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Joomla Version
      description: Welche Joomla Version wird genutzt?
      options:
        - 4.x (Empfohlen)
        - 3.10 (Achtung - Support Joomla 3.10 wird August 2023 eingestellt)
    validations:
      required: true
  - type: textarea
    id: information
    attributes:
      label: Zusätzliche Informationen
      description: Hier findest du Platz für weitere Informationen oder Links zum Forum etc.
    validations:
      required: false
